<?php
/**
 * Briefly.ai — Daily Digest PDF Generator
 * 
 * Route: /api/pdf
 * 
 * Generates a styled PDF of today's top stories.
 * Falls back to HTML if dompdf is not installed.
 */

require_once __DIR__ . '/../config.php';

$autoloadPath = __DIR__ . '/../vendor/autoload.php';
if (!file_exists($autoloadPath)) {
    generateHtmlFallback();
    exit;
}

require_once $autoloadPath;

use Dompdf\Dompdf;
use Dompdf\Options;

$db = getDB();
$stmt = $db->query("SELECT title, ai_summary, source_name, category, sentiment, published_at, original_url
                    FROM articles 
                    WHERE is_processed = 1 
                    ORDER BY published_at DESC 
                    LIMIT 10");
$articles = $stmt->fetchAll();

$date = date('F j, Y');
$storyCount = count($articles);

$html = <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 40px 50px; }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #1E293B; font-size: 11pt; line-height: 1.6;
        }
        .header { text-align: center; padding-bottom: 20px; border-bottom: 3px solid #10B981; margin-bottom: 30px; }
        .header h1 { font-size: 28pt; color: #0F172A; margin: 0; letter-spacing: -0.5px; }
        .header .subtitle { color: #10B981; font-size: 10pt; font-weight: 600; text-transform: uppercase; letter-spacing: 2px; margin-top: 5px; }
        .header .date { color: #64748B; font-size: 10pt; margin-top: 8px; }
        .story { margin-bottom: 25px; padding: 16px 20px; border-left: 4px solid #10B981; background: #F8FAFC; page-break-inside: avoid; }
        .story-number { color: #10B981; font-size: 9pt; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px; }
        .story h2 { font-size: 13pt; color: #0F172A; margin: 0 0 8px 0; line-height: 1.3; }
        .story p { color: #475569; font-size: 10pt; margin: 0 0 10px 0; }
        .story-meta { font-size: 8pt; color: #94A3B8; }
        .sentiment-positive { color: #10B981; font-weight: 600; }
        .sentiment-negative { color: #EF4444; font-weight: 600; }
        .sentiment-neutral  { color: #94A3B8; font-weight: 600; }
        .footer { text-align: center; padding-top: 20px; border-top: 1px solid #E2E8F0; margin-top: 30px; color: #94A3B8; font-size: 8pt; }
    </style>
</head>
<body>
    <div class="header">
        <h1>⚡ Briefly.ai</h1>
        <div class="subtitle">Daily Intelligence Briefing</div>
        <div class="date">{$date} — {$storyCount} stories</div>
    </div>
HTML;

foreach ($articles as $i => $article) {
    $num = $i + 1;
    $title = htmlspecialchars($article['title']);
    $summary = htmlspecialchars($article['ai_summary'] ?? 'Summary not available.');
    $source = htmlspecialchars($article['source_name'] ?? 'Unknown');
    $category = htmlspecialchars($article['category']);
    $sentiment = $article['sentiment'] ?? 'neutral';
    $sentimentLabel = ucfirst($sentiment);
    $sentimentIcon = match ($sentiment) {
        'positive' => '↑', 'negative' => '↓', default => '→',
    };
    $pubDate = $article['published_at'] ? date('M j, g:ia', strtotime($article['published_at'])) : '';

    $html .= <<<HTML
    <div class="story">
        <div class="story-number">{$category} · Story #{$num}</div>
        <h2>{$title}</h2>
        <p>{$summary}</p>
        <div class="story-meta">
            <span class="sentiment-{$sentiment}">{$sentimentIcon} {$sentimentLabel}</span>
             &nbsp;·&nbsp; {$source} &nbsp;·&nbsp; {$pubDate}
        </div>
    </div>
HTML;
}

$html .= <<<HTML
    <div class="footer">Generated by Briefly.ai — Your Automated Global Intelligence Hub<br>{$date}</div>
</body></html>
HTML;

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', false);
$options->set('defaultFont', 'Helvetica');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$filename = 'Briefly_AI_Briefing_' . date('Y-m-d') . '.pdf';
$dompdf->stream($filename, ['Attachment' => true]);


function generateHtmlFallback(): void {
    global $db;
    $db = getDB();
    $stmt = $db->query("SELECT title, ai_summary, source_name, category, sentiment, published_at FROM articles WHERE is_processed = 1 ORDER BY published_at DESC LIMIT 10");
    $articles = $stmt->fetchAll();
    $date = date('F j, Y');
    header('Content-Type: text/html; charset=utf-8');
    echo '<html><head><title>Briefly.ai Briefing - ' . $date . '</title>';
    echo '<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;color:#1E293B;}h1{text-align:center;color:#0F172A;}.story{margin:20px 0;padding:15px;border-left:4px solid #10B981;background:#F8FAFC;}.story h2{margin:0 0 8px;font-size:16px;}.story p{color:#475569;font-size:14px;}.note{text-align:center;background:#FEF3C7;padding:12px;border-radius:8px;margin:20px 0;font-size:14px;color:#92400E;}</style></head><body>';
    echo '<h1>⚡ Briefly.ai</h1><p style="text-align:center;color:#64748B;">Daily Intelligence Briefing — ' . $date . '</p>';
    echo '<div class="note">📦 Install <code>composer require dompdf/dompdf</code> to enable PDF downloads.</div>';
    foreach ($articles as $a) {
        echo '<div class="story"><h2>' . htmlspecialchars($a['title']) . '</h2><p>' . htmlspecialchars($a['ai_summary'] ?? '') . '</p><p style="font-size:12px;color:#94A3B8;">' . htmlspecialchars($a['source_name'] ?? '') . ' · ' . htmlspecialchars($a['category']) . '</p></div>';
    }
    echo '<p style="text-align:center;color:#94A3B8;font-size:12px;margin-top:30px;">Generated by Briefly.ai</p></body></html>';
}
